FIX Add missing devDependency
Problem:
I'm running node v.0.10.37.

When I run the following sequence of steps:
  git clone <this project>
  cd <this project>
  npm install
  npm install --only=dev
  grunt

I get
  $ grunt
  Loading "gjslint.js" tasks...ERROR
  >> Error: Cannot find module 'closure-linter-wrapper'

Solution:
Add 'closure-linter-wrapper' to devDependencies.